local weapons = {
    weapon_cz75a = {
        seed = 9788,
        recoilAng = 0.0,
        recoilAngVar = 120.0,
        recoilMagn = 31.0,
        recoilMagnVar = 6.0,
        cycle = 0.1,
        tIdle = 0.345388,
        primAmmo = 12.0
    },
    weapon_bizon = {
        seed = 36387,
        recoilAng = 0.0,
        recoilAngVar = 70.0,
        recoilMagn = 18.0,
        recoilMagnVar = 1.0,
        cycle = 0.08,
        tIdle = 0.331572,
        primAmmo = 64.0
    },
    weapon_mac10 = {
        seed = 34079,
        recoilAng = 0.0,
        recoilAngVar = 70.0,
        recoilMagn = 18.0,
        recoilMagnVar = 1.0,
        cycle = 0.075,
        tIdle = 0.399729,
        primAmmo = 30.0
    },
    weapon_mp7 = {
        seed = 61649,
        recoilAng = 0.0,
        recoilAngVar = 70.0,
        recoilMagn = 16.0,
        recoilMagnVar = 1.0,
        cycle = 0.08,
        tIdle = 0.437491,
        primAmmo = 30.0
    },
    weapon_mp5sd = {
        seed = 61649,
        recoilAng = 0.0,
        recoilAngVar = 70.0,
        recoilMagn = 16.0,
        recoilMagnVar = 1.0,
        cycle = 0.08,
        tIdle = 0.437491,
        primAmmo = 30.0
    },
    weapon_mp9 = {
        seed = 50729,
        recoilAng = 0.0,
        recoilAngVar = 70.0,
        recoilMagn = 19.0,
        recoilMagnVar = 1.0,
        cycle = 0.07,
        tIdle = 0.25789,
        primAmmo = 30.0
    },
    weapon_p90 = {
        seed = 6213,
        recoilAng = 0.0,
        recoilAngVar = 70.0,
        recoilMagn = 16.0,
        recoilMagnVar = 1.0,
        cycle = 0.07,
        tIdle = 0.372098,
        primAmmo = 50.0
    },
    weapon_ump45 = {
        seed = 59299,
        recoilAng = nil,
        recoilAngVar = 40.0,
        recoilMagn = 23.0,
        recoilMagnVar = 1.0,
        cycle = 0.09,
        tIdle = 0.349993,
        primAmmo = 25.0
    },
    weapon_ak47 = {
        seed = 223,
        recoilAng = 0.0,
        recoilAngVar = 70.0,
        recoilMagn = 30.0,
        recoilMagnVar = 0.0,
        cycle = 0.1,
        tIdle = 0.506,
        primAmmo = 30.0
    },
    weapon_aug = {
        seed = 24204,
        recoilAng = 0.0,
        recoilAngVar = 60.0,
        recoilMagn = 24.0,
        recoilMagnVar = 0.0,
        cycle = 0.1,
        tIdle = 0.429727,
        primAmmo = 30.0
    },
    weapon_famas = {
        seed = 39623,
        recoilAng = 0.0,
        recoilAngVar = 60.0,
        recoilMagn = 20.0,
        recoilMagnVar = 1.0,
        cycle = 0.09,
        tIdle = 0.5,
        primAmmo = 25.0
    },
    weapon_galilar = {
        seed = 51191,
        recoilAng = 0.0,
        recoilAngVar = 70.0,
        recoilMagn = 21.0,
        recoilMagnVar = 1.0,
        cycle = 0.09,
        tIdle = 0.5,
        primAmmo = 35.0
    },
    weapon_m4a1 = {
        seed = 38965,
        recoilAng = 0.0,
        recoilAngVar = 70.0,
        recoilMagn = 23.0,
        recoilMagnVar = 0.0,
        cycle = 0.09,
        tIdle = 0.466044,
        primAmmo = 30.0
    },
    weapon_sg556 = {
        seed = 43500,
        recoilAng = 0.0,
        recoilAngVar = 60.0,
        recoilMagn = 28.0,
        recoilMagnVar = 2.0,
        cycle = 0.11,
        tIdle = 0.452886,
        primAmmo = 30.0
    },
    weapon_g3sg1 = {
        seed = 29908,
        recoilAng = 0.0,
        recoilAngVar = 30.0,
        recoilMagn = 30.0,
        recoilMagnVar = 4.0,
        cycle = 0.25,
        tIdle = 0.544331,
        primAmmo = 20.0
    },
    weapon_scar20 = {
        seed = 19364,
        recoilAng = 0.0,
        recoilAngVar = 30.0,
        recoilMagn = 31.0,
        recoilMagnVar = 4.0,
        cycle = 0.25,
        tIdle = 0.544331,
        primAmmo = 20.0
    },
    weapon_xm1014 = {
        seed = 24862,
        recoilAng = 0.0,
        recoilAngVar = 20.0,
        recoilMagn = 80.0,
        recoilMagnVar = 20.0,
        cycle = 0.35,
        tIdle = 0.506569,
        primAmmo = 7.0
    },
    weapon_m249 = {
        seed = 50310,
        recoilAng = 0.0,
        recoilAngVar = 50.0,
        recoilMagn = 25.0,
        recoilMagnVar = 2.0,
        cycle = 0.08,
        tIdle = 0.828931,
        primAmmo = 100.0
    },
    weapon_negev = {
        seed = 57966,
        recoilAng = 0.0,
        recoilAngVar = 0.0,
        recoilMagn = 20.0,
        recoilMagnVar = 2.0,
        cycle = 0.075,
        tIdle = 0.1,
        primAmmo = 150.0
    },
    weapon_m4a1_silencer = {
        seed = 38965,
        recoilAng = 0.0,
        recoilAngVar = 65.0,
        recoilMagn = 25.0,
        recoilMagnVar = 3.0,
        cycle = 0.1,
        tIdle = 0.466044,
        primAmmo = 20.0
    },
    weapon_revolver = {
        seed = 12345,
        recoilAng = 0.0,
        recoilAngVar = 40.0,
        recoilMagn = 20.0,
        recoilMagnVar = 0.0,
        cycle = 0.5,
        tIdle = 0.8112,
        primAmmo = 8.0
    },
}
return weapons